app:
  name: my-app
  replicas: 1

image:
  repository: darkstar3110/node-app
  pullPolicy: IfNotPresent

container:
  port: 3000

service:
  type: LoadBalancer
  port: 3000

env:
  APP_VERSION: d9c638f8db98948ca80edd7b581556e44278bc1c
