app:
  name: my-app
  replicas: 1

image:
  repository: darkstar3110/node-app
  pullPolicy: IfNotPresent

container:
  port: 3000

service:
  type: LoadBalancer
  port: 3000

env:
  APP_VERSION: 0d9430eaaeef822f4b499ea8c62c5e21605a3ffa
