apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.app.name }}-service'
  labels:
    app: {{ .Values.app.name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
